### ISSUE TITLE
wrong comment?

### ISSUE THREAD

**Issue by Guid75** [analog-nico/hpp#16]
```
// Select the first parameter value
reqPart[paramKey] = paramValue[paramValue.length-1];
```

As far as I understand, this selects the _last_ parameter value.
Is the comment wrong or the assignement itself?

**Comment by analog-nico** [comment]
Thanks! You are right.

Fyi, the unit test ensures that the last value is chosen: https://github.com/analog-nico/hpp/blob/cdf0babacc2ad8635a70376a19d66705b8ab62be/test/spec/hpp.js#L103-L118
